apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastruscture-common
  namespace: flux-system
spec:
  interval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
path: ./infrastructure/common