---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: infrastuctures-common
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: main
  url: https://github.com/ccs1910/mesh-manifest-test/tree/main/infrastructures/common

