apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels: 
    mesh: santosoc-mesh
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
    gateway: ingress-gw

---
apiVersion: v1
kind: Namespace
metadata:
  name: curl
  labels: 
    mesh: santosoc-mesh
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: serve
  labels: 
    mesh: santosoc-mesh
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: blue
  labels: 
    mesh: santosoc-mesh
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: red
  labels: 
    mesh: santosoc-mesh
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: black
  labels: 
    mesh: santosoc-mesh
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: black2
  labels: 
    mesh: santosoc-mesh
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
