---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: gateway-route-eks
  namespace: nginx
spec:
  httpRoute:
    match:
      prefix: "/nginx/"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: nginx
