apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  labels:
    app: red
  namespace: red
spec:
  replicas: 3
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: red
    spec:
      containers:
      - name: red 
        image: 450360193046.dkr.ecr.us-west-2.amazonaws.com/santosoc-red:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5001
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        - name: grpc
          containerPort: 9999
          protocol: TCP
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
      # nodeSelector:
        # eks.amazonaws.com/nodegroup: linux2
      # affinity: {}