apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  labels:
    app: red
  namespace: red
  annotations:
    flux.weave.works/automated: "true"
spec:
  replicas: 1
  minReadySeconds: 3
  selector:
    matchLabels:
      app: red
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: red
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                - ng-consul-outposts
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                - key: alpha.eksctl.io/nodegroup-name
                  operator: In
                  values:
                  - ng-consul-frontend
      containers:
      - name: red 
        image: 450360193046.dkr.ecr.us-west-2.amazonaws.com/santosoc-red:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5001
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"


      # nodeSelector:
        # eks.amazonaws.com/nodegroup: linux2
      # affinity: {}