apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: red
  namespace: red
spec:
  awsName: red.santosoc.hosted.local
  provider:
    virtualNodeRef:
      name: red-app
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: red-router
  namespace: red
spec:
  listeners:
    - portMapping:
        port: 5001
        protocol: http
  routes:
    - name: route-to-red-app
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: red-app
              weight: 1
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: red-app
  namespace: red
spec:
  podSelector:
    matchLabels:
      app: red-app
  listeners:
    - portMapping:
        port: 5001
        protocol: http
  serviceDiscovery:
    awsCloudMap:
      namespaceName: santosoc.pvt.local
      serviceName: red
  backends:
    - virtualService:
        virtualServiceRef:
          namespace: nginx
          name: "nginx"