---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: gateway-route-red
  namespace: red
spec:
  httpRoute:
    match:
      prefix: "/red/"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: red
